In [2]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([
    [1000, 2, 5],
    [1500, 3, 10],
    [2000, 3, 2],
    [1200, 2, 8],
    [1800, 4, 15],
    [2200, 4, 3],
    [900, 1, 20],
    [1600, 3, 7],
])
y = np.array([200, 300, 400, 220, 350, 450, 150, 320])

# NORMALIZE: subtract mean, divide by std dev, for each column
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_norm = (X - X_mean) / X_std

print(X_norm)  # check it — values should now be roughly between -2 and 2

[[-1.19853331 -0.77459667 -0.65341026]
 [-0.05707301  0.25819889  0.21780342]
 [ 1.08438728  0.25819889 -1.17613847]
 [-0.74194919 -0.77459667 -0.13068205]
 [ 0.62780316  1.29099445  1.0890171 ]
 [ 1.54097139  1.29099445 -1.00189574]
 [-1.42682536 -1.80739223  1.96023079]
 [ 0.17121904  0.25819889 -0.30492479]]


In [3]:
n_features = X_norm.shape[1]
w = np.zeros(n_features)
b = 0.0

def predict(X, w, b):
    return X @ w + b

def loss(X, y, w, b):
    y_pred = predict(X, w, b)
    return np.mean((y_pred - y) ** 2)

learning_rate = 0.01   # back to a normal value now
epochs = 10000

for i in range(epochs):
    y_pred = predict(X_norm, w, b)
    error = y_pred - y

    dw = (2/len(X_norm)) * (X_norm.T @ error)
    db = (2/len(X_norm)) * np.sum(error)

    w = w - learning_rate * dw
    b = b - learning_rate * db

    if i % 1000 == 0:
        print(f"epoch {i}, loss: {loss(X_norm, y, w, b):.3f}")


epoch 0, loss: 94226.708
epoch 1000, loss: 31.171
epoch 2000, loss: 24.331
epoch 3000, loss: 24.148
epoch 4000, loss: 24.143
epoch 5000, loss: 24.143
epoch 6000, loss: 24.143
epoch 7000, loss: 24.143
epoch 8000, loss: 24.143
epoch 9000, loss: 24.143
